POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer token_here

{
    "title": "Titletest2",
    "author": "Titleauthor2",
    "url": "urltest3",
    "likes": 2
}