DELETE http://localhost:3003/api/blogs/6667147861c3678725fb86d8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld3VzZXIyIiwiaWQiOiI2NjY3MDk3ODg2MjY5ODBkYjZjNjE3Y2UiLCJpYXQiOjE3MTk1ODYwMTR9.FHqj4UBXwtZ34x6_toQ9N7OYwHatxFAHfbea2rrFIMM
